collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

include:
  - favicon.ico

plugins:
  - jekyll-sitemap

# Custom vars
github: https://github.com/EpiGenomicsCode
twitter: https://twitter.com/WilliamKMLai
